# Generated by Django 3.2.7 on 2021-10-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_academicperformance_date'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Приобретенный курс'),
        ),
    ]
