# Generated by Django 3.2.7 on 2021-10-24 03:39

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_academicperformance_date'),
        ('management', '0002_auto_20211007_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время затраты')),
                ('amount', models.IntegerField(verbose_name='Сумма затрат')),
            ],
            options={
                'verbose_name': 'Затрата',
                'verbose_name_plural': 'Затраты',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('place_of_study', models.CharField(max_length=50, verbose_name='Место учебы')),
                ('place_of_work', models.CharField(max_length=50, verbose_name='Место работы')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('result', models.CharField(choices=[('contract', 'Заключен договор'), ('passed', 'Сдал'), ('not_pass', 'Не сдал'), ('course', 'Рекомендованы курсы')], max_length=50, verbose_name='Результат собеседования')),
                ('comment', models.TextField(verbose_name='Комментарий рекрутера')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='comment',
            field=models.TextField(default=1, verbose_name='Комментарий рекрутера'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_request', models.CharField(choices=[('incoming_call', 'Входящий звонок'), ('outgoing_call', 'Исходящий звонок'), ('online', 'Онлайн'), ('visit', 'Визит')], max_length=50, verbose_name='Тип заявки')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработанная'), ('deleted', 'Удаленная')], default='new', max_length=50, verbose_name='Статус заявки')),
                ('purpose', models.CharField(blank=True, choices=[('price', 'Узнать цену'), ('meeting', 'Договориться о встрече'), ('info', 'Получить общую информацию'), ('details', 'Уточнить детали перед заключением договора'), ('repeat', 'Повторная консультация')], max_length=50, null=True, verbose_name='Цель заявки')),
                ('result', models.CharField(blank=True, choices=[('contract', 'Заключен договор'), ('meeting', 'Назначена встреча'), ('waiting_call', 'Ждет звонка'), ('will_think', 'Будет думать'), ('refusal', 'Отказ'), ('dissatisfied', 'Недовольный клиент')], max_length=50, null=True, verbose_name='Результат заявки')),
                ('remind', models.DateField(blank=True, null=True, verbose_name='Перезвонить / напомнить')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заявки')),
                ('comment', models.TextField(verbose_name='Комментарий менеджера')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.client', verbose_name='Клиент')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('date_and_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.client', verbose_name='Клиент')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
