# Generated by Django 3.2.7 on 2021-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20211029_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.TextField(blank=True, null=True, verbose_name='Город'),
        ),
    ]
