# Generated by Django 3.2.7 on 2021-10-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
    ]
