# Generated by Django 3.2.7 on 2021-11-02 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211102_1248'),
        ('management', '0014_alter_contract_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.profile')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': '07. Сотрудники',
            },
            bases=('mainapp.profile',),
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'Затрата', 'verbose_name_plural': '09. Затраты'},
        ),
        migrations.AlterModelOptions(
            name='costcategory',
            options={'verbose_name': 'Категория затрат', 'verbose_name_plural': '08. Категории затрат'},
        ),
    ]
