# Generated by Django 3.2.7 on 2021-11-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_profile_user_group'),
        ('management', '0016_alter_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий рекрутера'),
        ),
        migrations.AlterField(
            model_name='request',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий менеджера'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
