# Generated by Django 3.2.7 on 2021-11-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20211105_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='user',
        ),
    ]
