# Generated by Django 3.2.7 on 2021-11-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_response_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id оплаты'),
        ),
    ]
