# Generated by Django 3.2.7 on 2021-11-13 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211105_1615'),
        ('management', '0024_order_payment_response_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.student', verbose_name='Студент'),
        ),
    ]
