# Generated by Django 3.2.7 on 2022-01-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_order_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рекламная активность',
                'verbose_name_plural': '09. Рекламная активность',
            },
        ),
        migrations.CreateModel(
            name='AdvertisingActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория рекламной активности',
                'verbose_name_plural': '08. Категории рекламной активности',
            },
        ),
        migrations.AlterModelOptions(
            name='cost',
            options={'verbose_name': 'Затрата', 'verbose_name_plural': '11. Затраты'},
        ),
        migrations.AlterModelOptions(
            name='costcategory',
            options={'verbose_name': 'Категория затрат', 'verbose_name_plural': '10. Категории затрат'},
        ),
        migrations.AddField(
            model_name='cost',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период затрат по'),
        ),
        migrations.AddField(
            model_name='cost',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Период затрат с'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи'),
        ),
        migrations.AddField(
            model_name='cost',
            name='advertising_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.advertisingactivity'),
        ),
    ]
