# Generated by Django 3.2.7 on 2022-01-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_cost_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='advertising_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.advertisingactivity', verbose_name='Рекламная активность'),
        ),
    ]
