# Generated by Django 3.2.7 on 2022-01-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_cost_advertising_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.costcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Период затрат по'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='Период затрат с'),
        ),
    ]
