# Generated by Django 3.2.7 on 2022-01-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_auto_20220108_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategory',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
