# Generated by Django 3.2.7 on 2022-01-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_event_eventday_news'),
        ('management', '0030_costcategory_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата занесения в базу'),
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.student', verbose_name='Слушатель'),
        ),
    ]
