# Generated by Django 3.2.7 on 2022-01-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20220108_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Последний статус по заявкам'),
        ),
    ]
