# Generated by Django 3.2.7 on 2022-01-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_client_last_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisingactivity',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.advertisingactivitycategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
