# Generated by Django 3.2.7 on 2022-01-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_advertisingactivity_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='data',
            new_name='date',
        ),
    ]
