# Generated by Django 3.2.7 on 2022-01-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_auto_20220116_1649'),
        ('management', '0035_auto_20220109_1014'),
    ]

    operations = [
    ]
