# Generated by Django 3.2.7 on 2022-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_alter_request_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.CharField(blank=True, choices=[('price', 'Узнать цену'), ('meeting', 'Договориться о встрече'), ('info', 'Получить общую информацию'), ('details', 'Уточнить детали перед заключением договора'), ('repeat', 'Повторная консультация'), ('free_lesson', 'Записаться на пробный урок'), ('event', 'Запись на мероприятие'), ('chess_express', 'Шахматы - Экспресс обучение'), ('chess_pool', 'Шахматы - Блиц/пуля')], max_length=50, null=True, verbose_name='Цель заявки'),
        ),
    ]
