# Generated by Django 3.2.7 on 2022-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_request_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оплаченная сумма'),
        ),
    ]
