# Generated by Django 3.2.7 on 2022-03-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_alter_profile_is_show'),
        ('management', '0042_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event', verbose_name='Мероприятие'),
        ),
    ]
