# Generated by Django 3.2.7 on 2022-06-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_request_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='purpose',
            field=models.CharField(blank=True, choices=[('price', 'Узнать цену'), ('meeting', 'Договориться о встрече'), ('info', 'Получить общую информацию'), ('buy', 'Покупка курса'), ('details', 'Уточнить детали перед заключением договора'), ('repeat', 'Повторная консультация'), ('free_lesson', 'Записаться на пробный урок'), ('event', 'Запись на мероприятие'), ('chess_express', 'Шахматы - Экспресс обучение'), ('chess_pool', 'Шахматы - Блиц/пуля'), ('it_camp', 'ИТ Каникулы')], max_length=50, null=True, verbose_name='Цель заявки'),
        ),
    ]
