# Generated by Django 3.2.7 on 2022-06-08 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20220608_2204'),
        ('management', '0044_alter_request_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.city', verbose_name='Город'),
        ),
    ]
