# Generated by Django 3.2.7 on 2022-06-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_request_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
