# Generated by Django 3.2.7 on 2022-09-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_auto_20220905_2229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Заявка', 'verbose_name_plural': '04. Заявки'},
        ),
    ]
