# Generated by Django 3.2.7 on 2022-09-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_alter_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.staff', verbose_name='Менеджер'),
        ),
    ]
