# Generated by Django 3.2.7 on 2022-09-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0049_alter_academicperformance_grade'),
        ('management', '0049_contract_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='client_students', to='mainapp.Student', verbose_name='Студенты'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='В корзине'),
        ),
    ]
