# Generated by Django 3.2.7 on 2022-09-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_auto_20220919_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='speakers',
            new_name='students',
        ),
    ]
