# Generated by Django 3.2.7 on 2021-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210928_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата оценки'),
        ),
    ]
