# Generated by Django 3.2.7 on 2021-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_academicperformance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер учебного процесса'), ('sales_manager', 'Менеджер по продажам'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=50, verbose_name='Группа пользователей'),
        ),
    ]
