# Generated by Django 3.2.7 on 2021-09-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210905_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.profile')),
                ('education', models.CharField(max_length=100, verbose_name='Образование')),
                ('professional_activity', models.CharField(max_length=150, verbose_name='Профессиональная деятельность')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
            },
            bases=('mainapp.profile',),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Обучающийся', 'verbose_name_plural': 'Обучающиеся'},
        ),
    ]
