# Generated by Django 3.2.7 on 2021-09-05 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210905_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('admin', 'Админ'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=50, verbose_name='Группа пользователей'),
        ),
    ]
