# Generated by Django 3.2.7 on 2021-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210905_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='student',
            name='dream',
            field=models.TextField(blank=True, null=True, verbose_name='Мечта'),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.TextField(blank=True, null=True, verbose_name='Увлечения'),
        ),
    ]
