# Generated by Django 3.2.7 on 2021-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_profile_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
        migrations.DeleteModel(
            name='EducationalManager',
        ),
    ]
