# Generated by Django 3.2.7 on 2021-11-05 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_staff'),
        ('mainapp', '0007_auto_20211105_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='management.staff', verbose_name='Менеджер учебного процесса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=50, verbose_name='Группа пользователей'),
        ),
    ]
