# Generated by Django 3.2.7 on 2021-09-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210905_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.profile')),
            ],
            options={
                'verbose_name': 'Менеджер учебного процесса',
                'verbose_name_plural': 'Менеджеры учебного процесса',
            },
            bases=('mainapp.profile',),
        ),
    ]
