# Generated by Django 3.2.7 on 2021-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20211105_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='age_group',
            field=models.CharField(choices=[('children', 'Дети'), ('teens', 'Подростки'), ('adults', 'Взрослые')], default='children', max_length=50, verbose_name='Возрастная категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='complexity',
            field=models.CharField(choices=[('course', 'Курс'), ('profession', 'Профессия')], default='newbie', max_length=50, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=6, verbose_name='Длительность обучения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='education_type',
            field=models.CharField(choices=[('course', 'Курс'), ('profession', 'Профессия')], default='course', max_length=50, verbose_name='Тип обучения'),
        ),
    ]
