# Generated by Django 3.2.7 on 2021-11-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211114_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет блока курса (hex)'),
        ),
    ]
