# Generated by Django 3.2.7 on 2021-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user_group',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('admin', 'Админ'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=50, verbose_name='Группа пользователей'),
        ),
    ]
