# Generated by Django 3.2.7 on 2021-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211116_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текс навыка')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': '02. Обучение - Навыки',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='activity_mode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Режим заниятий'),
        ),
        migrations.AddField(
            model_name='course',
            name='who_is',
            field=models.TextField(blank=True, null=True, verbose_name='Блок кто такой'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='course_teachers', to='mainapp.Teacher', verbose_name='Преподаватели курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='mainapp.Skill', verbose_name='Вы научитесь'),
        ),
    ]
