# Generated by Django 3.2.7 on 2021-09-07 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20210906_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='professional_activity',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Профессиональная деятельность'),
        ),
    ]
