# Generated by Django 3.2.7 on 2021-12-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_course_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст новости')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('signature', models.CharField(max_length=100, verbose_name='Подпись к мероприятию')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/events', verbose_name='Изображение')),
                ('block_size', models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('big', 'Большой')], max_length=20, verbose_name='Размер блока')),
                ('program', models.ManyToManyField(blank=True, related_name='evert_days', to='mainapp.EventDay', verbose_name='Программа мероприятия')),
                ('speakers', models.ManyToManyField(blank=True, related_name='event_speakers', to='mainapp.Teacher', verbose_name='Спикеры')),
            ],
        ),
    ]
