# Generated by Django 3.2.7 on 2021-09-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=3000000, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер урока в курсе'),
        ),
    ]
