# Generated by Django 3.2.7 on 2022-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_event_eventday_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Вступление новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/news', verbose_name='Изображение'),
        ),
    ]
