# Generated by Django 3.2.7 on 2022-01-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20220109_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Мероприятия', 'verbose_name_plural': '05. Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventday',
            options={'verbose_name': 'Дни мероприятий', 'verbose_name_plural': '05. Мероприятия - Дни'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Новости', 'verbose_name_plural': '06. Новости'},
        ),
        migrations.AddField(
            model_name='event',
            name='block_image',
            field=models.BooleanField(default=False, verbose_name='Обложка блока картинкой'),
        ),
        migrations.AddField(
            model_name='event',
            name='color_hex',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цвет блока мероприятия (hex)'),
        ),
        migrations.AddField(
            model_name='eventday',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название (День '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='block_size',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('big', 'Большой')], default='small', max_length=20, verbose_name='Размер блока'),
        ),
    ]
