# Generated by Django 3.2.7 on 2021-09-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210907_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateTimeField(auto_created=True, verbose_name='Дата и время урока'),
        ),
    ]
