# Generated by Django 3.2.7 on 2021-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_timetable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время урока'),
        ),
    ]
