# Generated by Django 3.2.7 on 2021-09-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_timetable_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-date'], 'verbose_name': 'Рассписание урока', 'verbose_name_plural': 'Рассписание занятий'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание урока'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
