# Generated by Django 3.2.7 on 2022-01-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20220109_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verification',
            field=models.BooleanField(default=False, verbose_name='Верификация пройдена'),
        ),
    ]
