# Generated by Django 3.2.7 on 2022-01-11 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20220109_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_days', to='mainapp.event', verbose_name='Мероприятие'),
        ),
    ]
