# Generated by Django 3.2.7 on 2021-09-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
