# Generated by Django 3.2.7 on 2022-01-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20220116_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('salary_resume', models.CharField(max_length=100, verbose_name='Зарплата в резюме')),
                ('salary_junior', models.CharField(max_length=100, verbose_name='Зарплата Junior')),
                ('salary_middle', models.CharField(max_length=100, verbose_name='Зарплата Middle')),
                ('salary_senior', models.CharField(max_length=100, verbose_name='Зарплата Senior')),
                ('junior_name', models.CharField(default='Junior', max_length=100, verbose_name='Junior название блока')),
                ('middle_name', models.CharField(default='Middle', max_length=100, verbose_name='Middle название блока')),
                ('senior_name', models.CharField(default='Senior', max_length=100, verbose_name='Senior название блока')),
            ],
            options={
                'verbose_name': 'Провессия',
                'verbose_name_plural': '02. Обучение - Провессии',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='profession',
        ),
        migrations.AlterField(
            model_name='skill',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mainapp.course', verbose_name='Курс'),
        ),
        migrations.CreateModel(
            name='ProfessionSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текс навыка')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='mainapp.profession', verbose_name='Проессия')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': '02. Обучение - Профессии - Навыки',
            },
        ),
    ]
