# Generated by Django 3.2.7 on 2021-09-08 03:51

from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20210907_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperformance',
            options={'verbose_name': 'Успеваемость'},
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='absent',
            field=models.BooleanField(default=False, verbose_name='Отсутствие'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='classwork_grade',
            field=mainapp.models.IntegerRangeField(blank=True, null=True, verbose_name='Классная работа'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='examination_grade',
            field=mainapp.models.IntegerRangeField(blank=True, null=True, verbose_name='Экзамен'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='homework_grade',
            field=mainapp.models.IntegerRangeField(blank=True, null=True, verbose_name='Домашняя работа'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='late',
            field=models.BooleanField(default=False, verbose_name='Опоздание'),
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson', verbose_name='Урок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Обучающийся'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='test_grade',
            field=mainapp.models.IntegerRangeField(blank=True, null=True, verbose_name='Контрольная работа'),
        ),
    ]
