# Generated by Django 3.2.7 on 2022-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20220116_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Профессия'),
        ),
    ]
