# Generated by Django 3.2.7 on 2021-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_auto_20210908_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperformance',
            options={'verbose_name': 'Успеваемость', 'verbose_name_plural': 'Успеваемость'},
        ),
        migrations.AddField(
            model_name='academicperformance',
            name='date',
            field=models.DateField(default='2021-09-07', verbose_name='Дата оценки'),
            preserve_default=False,
        ),
    ]
