# Generated by Django 3.2.7 on 2022-01-16 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_course_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profession', verbose_name='Профессия'),
        ),
    ]
