# Generated by Django 3.2.7 on 2021-09-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20210908_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_group',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер учебного процесса'), ('teacher', 'Преподаватель'), ('student', 'Студент')], default='student', max_length=50, verbose_name='Группа пользователей'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/photos', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='mainapp.Profile', verbose_name='Лайки')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='photos',
            field=models.ManyToManyField(blank=True, to='mainapp.Photo', verbose_name='Фотографии'),
        ),
    ]
