# Generated by Django 3.2.7 on 2022-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_alter_course_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='how_is_the_training',
            field=models.TextField(blank=True, null=True, verbose_name='Как проходит обучение'),
        ),
    ]
