# Generated by Django 3.2.7 on 2021-09-09 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_auto_20210908_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='course',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/posters', verbose_name='Изображение курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_presentation',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на видеопрезентацию курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='files/courses/materials', verbose_name='Материалы курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория'),
        ),
    ]
