# Generated by Django 3.2.7 on 2022-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_category_how_is_the_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='in_main_page',
            field=models.BooleanField(default=False, verbose_name='Доступный курс'),
        ),
    ]
