# Generated by Django 3.2.7 on 2021-09-09 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0027_auto_20210909_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='EducationalManager',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_request_in',
            field=models.ManyToManyField(blank=True, related_name='in_friends', to=settings.AUTH_USER_MODEL, verbose_name='Входящие заявки в друзья'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_request_out',
            field=models.ManyToManyField(blank=True, related_name='out_friends', to=settings.AUTH_USER_MODEL, verbose_name='Исходящие заявки в друзья'),
        ),
    ]
