# Generated by Django 3.2.7 on 2021-09-10 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_auto_20210909_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
        migrations.AddField(
            model_name='student',
            name='group_list',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='mainapp.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='group_list',
            field=models.ManyToManyField(blank=True, related_name='teacher_groups', to='mainapp.Group', verbose_name='Группы'),
        ),
    ]
