# Generated by Django 3.2.7 on 2021-09-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20210910_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='for_profile',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='mainapp.profile', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
