# Generated by Django 3.2.7 on 2022-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_auto_20220308_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 1 (в шапке)'),
        ),
        migrations.AddField(
            model_name='event',
            name='text2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 2 (в шапке)'),
        ),
        migrations.AddField(
            model_name='event',
            name='text3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 3 (в шапке)'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_d',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст Д'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_o',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст О'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст Х'),
        ),
    ]
