# Generated by Django 3.2.7 on 2021-09-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_photo_for_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photo_list', to='mainapp.Photo', verbose_name='Фотографии'),
        ),
    ]
