# Generated by Django 3.2.7 on 2022-03-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20220313_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_owl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст в сове'),
        ),
    ]
