# Generated by Django 3.2.7 on 2022-03-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20220313_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Виден всем'),
        ),
    ]
