# Generated by Django 3.2.7 on 2022-03-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_profile_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_show',
        ),
    ]
