# Generated by Django 3.2.7 on 2022-03-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_teacher_is_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_show',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='Виден всем'),
        ),
    ]
