# Generated by Django 3.2.7 on 2022-03-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20220313_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Виден всем'),
        ),
    ]
