# Generated by Django 3.2.7 on 2021-09-11 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_auto_20210911_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicperformance',
            options={'verbose_name': 'Успеваемость', 'verbose_name_plural': '02. Обучение - Успеваемость'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': '02. Обучение - Категории'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': '02. Обучение - Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': '02. Обучение - Курсы'},
        ),
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': 'Диалог', 'verbose_name_plural': '03. Личные сообщения - Диалоги'},
        ),
        migrations.AlterModelOptions(
            name='dialogattachment',
            options={'verbose_name': 'Вложение', 'verbose_name_plural': '03. Личные сообщения - Вложения в диалогах'},
        ),
        migrations.AlterModelOptions(
            name='educationalmanager',
            options={'verbose_name': 'Менеджер учебного процесса', 'verbose_name_plural': '01. Пользователи - Менеджеры учебного процесса'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': '01. Пользователи - Группы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': '02. Обучение - Уроки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': '03. Личные сообщения - Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': '04. Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Обучающийся', 'verbose_name_plural': '01. Пользователи - Обучающиеся'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': '01. Пользователи - Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-date'], 'verbose_name': 'Рассписание урока', 'verbose_name_plural': '02. Обучение - Рассписание занятий'},
        ),
        migrations.AddField(
            model_name='dialog',
            name='group_founder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_founder', to='mainapp.profile', verbose_name='Основатель беседы'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Беседа'),
        ),
    ]
