# Generated by Django 3.2.7 on 2022-04-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20220403_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventday',
            name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='open_doors_day',
            field=models.BooleanField(default=False, verbose_name='День открытых дверей'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
