# Generated by Django 3.2.7 on 2021-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_auto_20210911_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название диалога'),
        ),
    ]
