# Generated by Django 3.2.7 on 2021-09-11 15:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_alter_dialog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время сообщения'),
            preserve_default=False,
        ),
    ]
