# Generated by Django 3.2.7 on 2022-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20220403_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='html_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для поисковиков'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
