# Generated by Django 3.2.7 on 2021-09-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_message_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='mainapp.Profile', verbose_name='Участники диалога'),
        ),
    ]
