# Generated by Django 3.2.7 on 2021-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_alter_dialog_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на профиль instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vk_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на профиль vk.com'),
        ),
    ]
