# Generated by Django 3.2.7 on 2022-06-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_auto_20220608_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='map_frame',
            field=models.TextField(blank=True, null=True, verbose_name='Код яндекс карты'),
        ),
        migrations.AddField(
            model_name='city',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
    ]
