# Generated by Django 3.2.7 on 2022-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_auto_20220617_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='group_courses', to='mainapp.Course', verbose_name='Курсы'),
        ),
    ]
