# Generated by Django 3.2.7 on 2022-08-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_group_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
