# Generated by Django 3.2.7 on 2021-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видеозапись урока'),
        ),
    ]
