# Generated by Django 3.2.7 on 2022-09-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_timetable_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.CharField(default='default', max_length=100, verbose_name='Название предмета'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.lesson', verbose_name='Урок'),
        ),
    ]
