# Generated by Django 3.2.7 on 2021-09-19 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_auto_20210919_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='mainapp.dialog', verbose_name='Диалог'),
        ),
    ]
