# Generated by Django 3.2.7 on 2021-09-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_alter_message_dialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_message', to='mainapp.message', verbose_name='Последнее сообщение'),
        ),
    ]
