# Generated by Django 3.2.7 on 2022-09-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20220904_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['-date'], 'verbose_name': 'Расписание урока', 'verbose_name_plural': '02. Обучение - Расписание занятий'},
        ),
        migrations.AddField(
            model_name='lesson',
            name='material_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на материалы'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='material_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на материалы'),
        ),
    ]
