# Generated by Django 3.2.7 on 2021-09-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_photo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_message',
            field=models.BooleanField(default=False, verbose_name='Системное сообщение'),
        ),
    ]
