# Generated by Django 3.2.7 on 2022-09-16 20:42

from django.db import migrations
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0048_timetable_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperformance',
            name='grade',
            field=mainapp.models.IntegerRangeField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
