# Generated by Django 3.2.7 on 2021-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20210925_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram_slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка на профиль vk.com'),
        ),
    ]
