# Generated by Django 3.2.7 on 2022-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20221106_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество уроков'),
        ),
    ]
