# Generated by Django 3.2.7 on 2021-09-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_auto_20210925_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogattachment',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.profile', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='dialogattachment',
            name='file',
            field=models.FileField(upload_to='files/messages_files', verbose_name='Файл'),
        ),
    ]
