# Generated by Django 3.2.7 on 2022-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_alter_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_disable', models.ImageField(upload_to='images/achievement', verbose_name='Изображение не активной награды')),
                ('image_enable', models.ImageField(upload_to='images/achievement', verbose_name='Изображение активной награды')),
            ],
            options={
                'verbose_name': 'Ачивки',
                'verbose_name_plural': '01. Пользователи - Ачивки',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='achievement',
            field=models.ManyToManyField(blank=True, related_name='achievement', to='mainapp.Achievement', verbose_name='ачивки'),
        ),
    ]
