# Generated by Django 3.2.7 on 2022-12-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20221119_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': '02. Обучение - Комментарии к уроку',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='comments',
            field=models.ManyToManyField(blank=True, to='mainapp.LessonComment', verbose_name='Комментарии студентов'),
        ),
    ]
