# Generated by Django 3.2.7 on 2022-12-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0055_auto_20221203_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicperformance',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
