# Generated by Django 3.2.7 on 2022-12-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0056_academicperformance_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='available_students',
            field=models.ManyToManyField(blank=True, to='mainapp.Student', verbose_name='Обучающиеся кому доступен урок'),
        ),
    ]
