from django.contrib.auth import views
from django.urls import path

from management.views import (
    MainView,
    ProfileLoginView,
    ClientsListView,
    ClientDetailView,
    CreateClientView,
    ContractListView,
    ContractDetailView,
    CreateContractView,
    VacancyListView,
    VacancyDetailView,
    CreateVacancyView,
    InterviewListView,
    InterviewDetailView,
    CreateInterviewView,
    OrderListView,
    OrderDetailView,
    CreateOrderView,
    RequestListView,
    RequestDetailView,
    CreateRequestView,
    CourseListView,
    CourseDetailView,
    CreateCourseView,
    CreateLessonView,
    TimeTableListView,
    CreateTimeTableView,
    AcademicPerformanceListView,
    CreateAcademicPerformanceView,
)


urlpatterns = [
    path('', MainView.as_view(), name='home'),
    path('auth/', ProfileLoginView.as_view(), name='auth'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('clients/', ClientsListView.as_view(), name='clients'),
    path('clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create', CreateClientView.as_view(), name='create_client'),
    path('requests/', RequestListView.as_view(), name='requests'),
    path('requests/<int:pk>/', RequestDetailView.as_view(), name='requests_detail'),
    path('requests/create/', CreateRequestView.as_view(), name='create_request'),
    path('contracts/', ContractListView.as_view(), name='contracts'),
    path('contracts/<int:pk>/', ContractDetailView.as_view(), name='contracts_detail'),
    path('contracts/create/', CreateContractView.as_view(), name='create_contract'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='orders_detail'),
    path('orders/create/', CreateOrderView.as_view(), name='create_order'),
    path('vacancy/', VacancyListView.as_view(), name='vacancy'),
    path('vacancy/<int:pk>/', VacancyDetailView.as_view(), name='vacancy_detail'),
    path('vacancy/create/', CreateVacancyView.as_view(), name='create_vacancy'),
    path('interview/', InterviewListView.as_view(), name='interview'),
    path('interview/<int:pk>/', InterviewDetailView.as_view(), name='interview_detail'),
    path('interview/create/', CreateInterviewView.as_view(), name='create_interview'),
    path('courses/', CourseListView.as_view(), name='courses'),
    path('courses/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),
    path('courses/create/', CreateCourseView.as_view(), name='create_course'),
    path('courses/lessons/create/', CreateLessonView.as_view(), name='create_lesson'),
    path('academic-performance/', AcademicPerformanceListView.as_view(), name='academic_performance'),
    path('academic-performance/create/', CreateAcademicPerformanceView.as_view(), name='create_academic_performance'),
    path('timetable/', TimeTableListView.as_view(), name='timetable'),
    path('timetable/create/', CreateTimeTableView.as_view(), name='create_timetable'),
]
